var hierarchy =
[
    [ "morph::app::App&lt; Title, Menu, Screens &gt;", "d8/d09/structmorph_1_1app_1_1App.html", null ],
    [ "morph::app::AppTraits&lt; A &gt;", "d9/dfd/structmorph_1_1app_1_1AppTraits.html", null ],
    [ "morph::app::FormScreen&lt; Id, Action &gt;", "d6/d0e/structmorph_1_1app_1_1FormScreen.html", null ],
    [ "morph::app::MenuEntry&lt; Label, ScreenId &gt;", "dc/d5e/structmorph_1_1app_1_1MenuEntry.html", null ],
    [ "morph::app::WizardScreen&lt; Id, Wizard &gt;", "dc/d11/structmorph_1_1app_1_1WizardScreen.html", null ],
    [ "morph::async::Completion&lt; T &gt;", "dd/de7/classmorph_1_1async_1_1Completion.html", null ],
    [ "morph::backend::detail::IBackend", null, [
      [ "morph::backend::LocalBackend", "d8/dfd/classmorph_1_1backend_1_1LocalBackend.html", null ],
      [ "morph::backend::SimulatedRemoteBackend", "d4/d10/classmorph_1_1backend_1_1SimulatedRemoteBackend.html", null ],
      [ "morph::net::SocketBackend", "d5/d98/classmorph_1_1net_1_1SocketBackend.html", null ],
      [ "morph::qt::QtWebSocketBackend", "d4/d0b/classmorph_1_1qt_1_1QtWebSocketBackend.html", null ]
    ] ],
    [ "morph::backend::HealthStatus", "d1/d59/structmorph_1_1backend_1_1HealthStatus.html", null ],
    [ "morph::backend::LimitPolicy", "de/dc7/structmorph_1_1backend_1_1LimitPolicy.html", null ],
    [ "morph::backend::RemoteServer", "d4/dc1/classmorph_1_1backend_1_1RemoteServer.html", null ],
    [ "morph::bridge::ActionExecuteRegistry", "db/dd1/classmorph_1_1bridge_1_1ActionExecuteRegistry.html", null ],
    [ "morph::bridge::AllowShared", "dd/dfb/structmorph_1_1bridge_1_1AllowShared.html", null ],
    [ "morph::bridge::Bridge", "d0/ddc/classmorph_1_1bridge_1_1Bridge.html", null ],
    [ "morph::bridge::BridgeHandler&lt; Model, Sharing &gt;", "d4/d7b/classmorph_1_1bridge_1_1BridgeHandler.html", null ],
    [ "morph::bridge::NoSharing", "d8/d38/structmorph_1_1bridge_1_1NoSharing.html", null ],
    [ "morph::detail::FixedString&lt; N &gt;", "df/d52/structmorph_1_1detail_1_1FixedString.html", null ],
    [ "morph::exec::IExecutor", "d4/d49/structmorph_1_1exec_1_1IExecutor.html", [
      [ "morph::exec::MainThreadExecutor", "d1/db0/classmorph_1_1exec_1_1MainThreadExecutor.html", null ],
      [ "morph::exec::ThreadPoolExecutor", "d9/db3/classmorph_1_1exec_1_1ThreadPoolExecutor.html", null ],
      [ "morph::qt::QtExecutor", "d4/d30/classmorph_1_1qt_1_1QtExecutor.html", null ]
    ] ],
    [ "morph::flows::Bind&lt; Field, Path &gt;", "d2/daf/structmorph_1_1flows_1_1Bind.html", null ],
    [ "morph::flows::detail::AllDistinct&lt; Ts &gt;", "d6/d90/structmorph_1_1flows_1_1detail_1_1AllDistinct.html", null ],
    [ "morph::flows::detail::AllDistinct&lt; T, Rest... &gt;", "de/d87/structmorph_1_1flows_1_1detail_1_1AllDistinct_3_01T_00_01Rest_8_8_8_01_4.html", null ],
    [ "morph::flows::FlowSession&lt; Model, Steps &gt;", "d1/d5c/classmorph_1_1flows_1_1FlowSession.html", null ],
    [ "morph::flows::Wizard&lt; Title, Steps &gt;", "d6/d94/structmorph_1_1flows_1_1Wizard.html", null ],
    [ "morph::flows::WizardStep&lt; Action, Title, Binds &gt;", "d8/d94/structmorph_1_1flows_1_1WizardStep.html", null ],
    [ "morph::flows::WizardTraits&lt; W &gt;", "de/d61/structmorph_1_1flows_1_1WizardTraits.html", null ],
    [ "morph::forms::And&lt; A, Conds &gt;", "d3/d81/structmorph_1_1forms_1_1And.html", null ],
    [ "morph::forms::AtLeastOneOf&lt; A, Vs &gt;", "de/d4f/structmorph_1_1forms_1_1AtLeastOneOf.html", null ],
    [ "morph::forms::Choice&lt; T, OptionsAction, ValueField, LabelField, DependsOn &gt;", "df/d65/structmorph_1_1forms_1_1Choice.html", null ],
    [ "morph::forms::Engaged&lt; V, A &gt;", "dd/d6b/structmorph_1_1forms_1_1Engaged.html", null ],
    [ "morph::forms::Equals&lt; V, A, L &gt;", "db/ddd/structmorph_1_1forms_1_1Equals.html", null ],
    [ "morph::forms::ExactlyOneOf&lt; A, Vs &gt;", "d9/d06/structmorph_1_1forms_1_1ExactlyOneOf.html", null ],
    [ "morph::forms::FieldGroup", "d1/d66/structmorph_1_1forms_1_1FieldGroup.html", null ],
    [ "morph::forms::FieldMeta", "df/db5/structmorph_1_1forms_1_1FieldMeta.html", null ],
    [ "morph::forms::FieldSpan", "d4/d7e/structmorph_1_1forms_1_1FieldSpan.html", null ],
    [ "morph::forms::Greater&lt; V, A &gt;", "d1/d59/structmorph_1_1forms_1_1Greater.html", null ],
    [ "morph::forms::GreaterOrEqual&lt; V, A &gt;", "d1/df3/structmorph_1_1forms_1_1GreaterOrEqual.html", null ],
    [ "morph::forms::Less&lt; V, A &gt;", "dd/da0/structmorph_1_1forms_1_1Less.html", null ],
    [ "morph::forms::LessOrEqual&lt; V, A &gt;", "d3/d3c/structmorph_1_1forms_1_1LessOrEqual.html", null ],
    [ "morph::forms::Multiline", "dc/df3/structmorph_1_1forms_1_1Multiline.html", null ],
    [ "morph::forms::MutuallyExclusive&lt; A, Vs &gt;", "dc/d20/structmorph_1_1forms_1_1MutuallyExclusive.html", null ],
    [ "morph::forms::Not&lt; A, Cond &gt;", "d1/db1/structmorph_1_1forms_1_1Not.html", null ],
    [ "morph::forms::NotEngaged&lt; V, A &gt;", "d9/d86/structmorph_1_1forms_1_1NotEngaged.html", null ],
    [ "morph::forms::Or&lt; A, Conds &gt;", "d4/d8d/structmorph_1_1forms_1_1Or.html", null ],
    [ "morph::forms::Ranged&lt; Min, Max, Step &gt;", "d7/d6d/structmorph_1_1forms_1_1Ranged.html", null ],
    [ "morph::forms::ReadonlyWhen&lt; V, A, Cond &gt;", "dd/d29/structmorph_1_1forms_1_1ReadonlyWhen.html", null ],
    [ "morph::forms::RequiredWhen&lt; V, A, Cond &gt;", "d6/da7/structmorph_1_1forms_1_1RequiredWhen.html", null ],
    [ "morph::forms::RuleList&lt; Rules &gt;", "d3/d8b/structmorph_1_1forms_1_1RuleList.html", null ],
    [ "morph::forms::VisibleWhen&lt; V, A, Cond &gt;", "d8/d10/structmorph_1_1forms_1_1VisibleWhen.html", null ],
    [ "morph::journal::detail::EscapingWriteOpts", "da/d0c/structmorph_1_1journal_1_1detail_1_1EscapingWriteOpts.html", null ],
    [ "morph::journal::IActionLog", "df/d4e/structmorph_1_1journal_1_1IActionLog.html", [
      [ "morph::journal::FileActionLog", "d0/d2e/classmorph_1_1journal_1_1FileActionLog.html", null ],
      [ "morph::journal::InMemoryActionLog", "d4/dc5/classmorph_1_1journal_1_1InMemoryActionLog.html", null ],
      [ "morph::journal::SessionLog", "da/d23/classmorph_1_1journal_1_1SessionLog.html", null ]
    ] ],
    [ "morph::journal::LogEntry", "de/d2a/structmorph_1_1journal_1_1LogEntry.html", null ],
    [ "morph::journal::OutboxRelay", "d9/d67/structmorph_1_1journal_1_1OutboxRelay.html", null ],
    [ "morph::journal::OutboxRelayResult", "d8/da5/structmorph_1_1journal_1_1OutboxRelayResult.html", null ],
    [ "morph::journal::ScopedActionLog", "de/d66/classmorph_1_1journal_1_1ScopedActionLog.html", null ],
    [ "morph::log::ScopedLoggerOverride", "d2/da9/classmorph_1_1log_1_1ScopedLoggerOverride.html", null ],
    [ "morph::math::DecimalPlaces", "da/d03/structmorph_1_1math_1_1DecimalPlaces.html", null ],
    [ "morph::math::Denominator", "de/d17/structmorph_1_1math_1_1Denominator.html", null ],
    [ "morph::math::Numerator", "d7/d45/structmorph_1_1math_1_1Numerator.html", null ],
    [ "morph::math::Rational", "d2/d5c/structmorph_1_1math_1_1Rational.html", null ],
    [ "morph::math::Rational::Wire", "d7/dbe/structmorph_1_1math_1_1Rational_1_1Wire.html", null ],
    [ "morph::model::ActionKeyTraits&lt; Action &gt;", "d5/d19/structmorph_1_1model_1_1ActionKeyTraits.html", null ],
    [ "morph::model::ActionLogPolicy&lt; Action &gt;", "da/dba/structmorph_1_1model_1_1ActionLogPolicy.html", null ],
    [ "morph::model::ActionTraits&lt; Action &gt;", "d5/d09/structmorph_1_1model_1_1ActionTraits.html", null ],
    [ "morph::model::ActionValidator&lt; Action &gt;", "d5/d92/structmorph_1_1model_1_1ActionValidator.html", null ],
    [ "morph::model::ModelKeyTraits&lt; Model &gt;", "d2/ded/structmorph_1_1model_1_1ModelKeyTraits.html", null ],
    [ "morph::model::ModelTraits&lt; Model &gt;", "d2/d14/structmorph_1_1model_1_1ModelTraits.html", null ],
    [ "morph::net::SocketBackendConfig", "db/d8e/structmorph_1_1net_1_1SocketBackendConfig.html", null ],
    [ "morph::net::SocketServer", "dc/d9a/classmorph_1_1net_1_1SocketServer.html", null ],
    [ "morph::net::SocketServerConfig", "d4/db0/structmorph_1_1net_1_1SocketServerConfig.html", null ],
    [ "morph::observe::MetricEvent", "de/dce/structmorph_1_1observe_1_1MetricEvent.html", null ],
    [ "morph::observe::ScopedObserveOverride", "d8/dbe/classmorph_1_1observe_1_1ScopedObserveOverride.html", null ],
    [ "morph::observe::TraceSink", "d5/d5e/structmorph_1_1observe_1_1TraceSink.html", null ],
    [ "morph::offline::IOfflineQueue", "d0/dc5/structmorph_1_1offline_1_1IOfflineQueue.html", [
      [ "morph::offline::FileOfflineQueue", "df/d07/classmorph_1_1offline_1_1FileOfflineQueue.html", null ],
      [ "morph::offline::InMemoryOfflineQueue", "d6/d5e/classmorph_1_1offline_1_1InMemoryOfflineQueue.html", null ],
      [ "morph::offline::SqliteOfflineQueue", "df/d53/classmorph_1_1offline_1_1SqliteOfflineQueue.html", null ]
    ] ],
    [ "morph::offline::NetworkMonitor", "db/dee/classmorph_1_1offline_1_1NetworkMonitor.html", null ],
    [ "morph::offline::NetworkMonitorConfig", "d3/d96/structmorph_1_1offline_1_1NetworkMonitorConfig.html", null ],
    [ "morph::offline::QueueItem", "d0/df8/structmorph_1_1offline_1_1QueueItem.html", null ],
    [ "morph::offline::ReconnectCoordinator", "d9/dc4/classmorph_1_1offline_1_1ReconnectCoordinator.html", null ],
    [ "morph::offline::ReconnectCoordinator::Deps", "da/d4f/structmorph_1_1offline_1_1ReconnectCoordinator_1_1Deps.html", null ],
    [ "morph::offline::ReconnectCoordinatorConfig", "d0/d03/structmorph_1_1offline_1_1ReconnectCoordinatorConfig.html", null ],
    [ "morph::offline::SyncResult", "de/d6e/structmorph_1_1offline_1_1SyncResult.html", null ],
    [ "morph::offline::SyncWorker", "d3/d55/classmorph_1_1offline_1_1SyncWorker.html", null ],
    [ "morph::qt::forms::FormsControllerCore&lt; Model &gt;", "d0/d26/classmorph_1_1qt_1_1forms_1_1FormsControllerCore.html", null ],
    [ "morph::qt::QtWebSocketBackendConfig", "d1/d2f/structmorph_1_1qt_1_1QtWebSocketBackendConfig.html", null ],
    [ "morph::qt::QtWebSocketServer", "d9/d42/classmorph_1_1qt_1_1QtWebSocketServer.html", null ],
    [ "morph::qt::QtWebSocketServerConfig", "de/d9a/structmorph_1_1qt_1_1QtWebSocketServerConfig.html", null ],
    [ "morph::session::Context", "dd/d85/structmorph_1_1session_1_1Context.html", null ],
    [ "morph::session::detail::EscapingWriteOpts", "de/d41/structmorph_1_1session_1_1detail_1_1EscapingWriteOpts.html", null ],
    [ "morph::session::detail::ScopedContext", "dd/dca/classmorph_1_1session_1_1detail_1_1ScopedContext.html", null ],
    [ "morph::session::IAuthorizer", "d5/d07/structmorph_1_1session_1_1IAuthorizer.html", [
      [ "morph::session::AllowAllAuthorizer", "dd/d85/structmorph_1_1session_1_1AllowAllAuthorizer.html", null ],
      [ "morph::session::SigningAuthorizer", "db/dd9/classmorph_1_1session_1_1SigningAuthorizer.html", null ]
    ] ],
    [ "morph::session::Principal", "d0/d26/structmorph_1_1session_1_1Principal.html", null ],
    [ "morph::session::SessionToken", "d8/dd5/structmorph_1_1session_1_1SessionToken.html", null ],
    [ "morph::session::TokenIssuer", "dc/de7/classmorph_1_1session_1_1TokenIssuer.html", null ],
    [ "morph::session::TokenVerifier", "d5/dc7/classmorph_1_1session_1_1TokenVerifier.html", null ],
    [ "morph::time::DateTime", "d5/d44/structmorph_1_1time_1_1DateTime.html", null ],
    [ "morph::time::ScopedNowOverride", "d3/d86/classmorph_1_1time_1_1ScopedNowOverride.html", null ],
    [ "morph::time::Timestamp", "db/dec/structmorph_1_1time_1_1Timestamp.html", null ],
    [ "morph::units::Quantity&lt; U, DeclaredDecimals &gt;", "d5/dda/structmorph_1_1units_1_1Quantity.html", null ],
    [ "morph::units::Quantity&lt; U &gt;", "d5/dda/structmorph_1_1units_1_1Quantity.html", [
      [ "morph::units::NamedQuantity< Name, U >", "d1/d58/structmorph_1_1units_1_1NamedQuantity.html", null ]
    ] ],
    [ "morph::units::QuantityBounds", "df/dca/structmorph_1_1units_1_1QuantityBounds.html", null ],
    [ "morph::units::UnitAlternative&lt; E &gt;", "d5/d23/structmorph_1_1units_1_1UnitAlternative.html", null ],
    [ "morph::units::UnitMeta", "d8/dab/structmorph_1_1units_1_1UnitMeta.html", null ],
    [ "morph::units::UnitRelation&lt; E &gt;", "da/d8f/structmorph_1_1units_1_1UnitRelation.html", null ],
    [ "morph::units::UnitTraits&lt; E &gt;", "de/d93/structmorph_1_1units_1_1UnitTraits.html", null ],
    [ "morph::util::detail::IsTagged&lt; T &gt;", "d7/d54/structmorph_1_1util_1_1detail_1_1IsTagged.html", null ],
    [ "morph::util::Tagged&lt; T, Tag &gt;", "dc/d7a/structmorph_1_1util_1_1Tagged.html", null ],
    [ "morph::views::ActionDescriptor", "d0/d03/structmorph_1_1views_1_1ActionDescriptor.html", null ],
    [ "morph::views::BindEntry", "d9/dea/structmorph_1_1views_1_1BindEntry.html", null ],
    [ "morph::views::CollectionView", "df/d26/structmorph_1_1views_1_1CollectionView.html", null ],
    [ "morph::views::ColumnOverride", "dd/da5/structmorph_1_1views_1_1ColumnOverride.html", null ],
    [ "morph::views::MasterDetailView", "d7/dd6/structmorph_1_1views_1_1MasterDetailView.html", null ],
    [ "morph::views::ViewRegistry", "db/d4f/classmorph_1_1views_1_1ViewRegistry.html", null ],
    [ "morph::views::ViewTraits&lt; V &gt;", "db/db9/structmorph_1_1views_1_1ViewTraits.html", null ],
    [ "morph::wire::detail::EscapingWriteOpts", "de/d8d/structmorph_1_1wire_1_1detail_1_1EscapingWriteOpts.html", null ],
    [ "morph::wire::Envelope", "d5/d77/structmorph_1_1wire_1_1Envelope.html", null ],
    [ "morph::wire::ProtocolRange", "da/d37/structmorph_1_1wire_1_1ProtocolRange.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "morph::backend::BackendChangedError", "dd/ddc/structmorph_1_1backend_1_1BackendChangedError.html", null ],
        [ "morph::backend::BridgeDestroyedError", "db/d09/structmorph_1_1backend_1_1BridgeDestroyedError.html", null ],
        [ "morph::backend::ClientTimeoutError", "d5/d8f/structmorph_1_1backend_1_1ClientTimeoutError.html", null ],
        [ "morph::backend::DisconnectedError", "d3/d73/structmorph_1_1backend_1_1DisconnectedError.html", null ],
        [ "morph::backend::TimeoutError", "d5/d80/structmorph_1_1backend_1_1TimeoutError.html", null ],
        [ "morph::forms::QuantityDecodeError", "d9/d1c/structmorph_1_1forms_1_1QuantityDecodeError.html", null ],
        [ "morph::journal::SerializationError", "d6/d23/structmorph_1_1journal_1_1SerializationError.html", null ],
        [ "morph::model::ValidationError", "d7/d1a/structmorph_1_1model_1_1ValidationError.html", null ],
        [ "morph::offline::FileOfflineQueueError", "d6/d90/structmorph_1_1offline_1_1FileOfflineQueueError.html", null ],
        [ "morph::offline::SqliteOfflineQueueError", "dc/d46/structmorph_1_1offline_1_1SqliteOfflineQueueError.html", null ],
        [ "morph::session::TokenIssuanceError", "d1/da4/structmorph_1_1session_1_1TokenIssuanceError.html", null ]
      ] ]
    ] ]
];