// SPDX-License-Identifier: Apache-2.0
//
// A list/table + master-detail screen composed entirely from existing
// action-forms (DynamicForm), driven by a view-schema document
// (v-kind/v-title/v-query/v-rowKey/v-columns/v-rowAction/v-actions)
// generated by morph::views::viewSchemaJson<V>() — see
// docs/spec/forms/views.md. Nothing here knows the view's concrete C++ row
// or action types; the schema is the only contract, exactly as
// DynamicForm.qml treats the per-action schema.
//
// Populate/edit/delete/create are ordinary controller.submitIfValid() calls
// over the same executeJson path every DynamicForm uses — no new dispatch
// mechanism. After an edit/delete/create resolves, the query re-runs to
// refresh the table (docs/spec/forms/views.md, "Dispatch: the screen is
// still just action calls").

pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Frame {
    id: root

    property string viewId
    property var view
    property var schemas
    property var controller

    property var rows: []
    property var editorRow: null   // the row currently open for edit, or null

    readonly property bool isMasterDetail: root.view["v-kind"] === "master-detail"
    readonly property var visibleColumns: (root.view["v-columns"] || []).filter(c => !c["v-hidden"])
    readonly property var rowScopeActions: (root.view["v-actions"] || []).filter(a => a.scope === "row")
    readonly property var collectionScopeActions: (root.view["v-actions"] || []).filter(a => a.scope === "collection")

    function opt(value, fallback) {
        return value === undefined ? fallback : value
    }

    // DynamicForm.qml's own fields never need to be *externally* prefilled
    // (every field the shipped renderer draws starts from typed user input,
    // building up form.fieldValues one keystroke/selection at a time) --
    // form.setFieldValue(name, text) updates that internal reactive state
    // (and so participates correctly in the required-field/auto-fire gate),
    // but it does not, by itself, push the value back onto a plain
    // TextField's displayed `text` (there is no such binding in
    // DynamicForm.qml, by design: every other control already owns writing
    // its own `text`/selection from the *user's* input). Reusing
    // DynamicForm.qml unmodified as the row editor (per docs/spec/forms/
    // views.md) means CollectionView must drive the same effect the same
    // way a user would: locate the actual `field_<name>` TextField instance
    // and set its `text`, whose own `onTextChanged` handler then calls
    // form.setFieldValue for us. This only reaches the default
    // (`objectName: "field_" + name`) TextField control DynamicForm.qml
    // draws for a plain scalar field -- a bound field rendered as a Choice/
    // DateTime/Slider/Multiline/radio-group control (or overridden via
    // SlotRegistry) is not currently prefillable this way; see
    // docs/spec/forms/views.md, "Limitations".
    function findControlByObjectName(item, name) {
        if (!item)
            return null
        if (item.objectName === name)
            return item
        const kids = item.children || []
        for (let i = 0; i < kids.length; ++i) {
            const found = root.findControlByObjectName(kids[i], name)
            if (found)
                return found
        }
        return null
    }

    // Same array-or-first-array-member extraction DynamicForm.qml's
    // optionRows() applies to a query action's result.
    function extractRows(result) {
        if (Array.isArray(result))
            return result
        for (const key in result) {
            if (Array.isArray(result[key]))
                return result[key]
        }
        return []
    }

    function populate() {
        if (root.controller)
            root.controller.submitIfValid(root.view["v-query"], "{}")
    }

    // A cell whose column carries x-decimalPlaces/ExtUnits (a Quantity field)
    // formats like DynamicForm.qml's humanize(); an absent/omitted-empty
    // field (docs/spec/util/quantity_type.md: an empty Quantity is omitted
    // from the wire object, not "field":null) renders blank.
    function formatCell(row, column) {
        const value = row[column.field]
        if (value === undefined || value === null)
            return ""
        if (value && value.num !== undefined && value.den !== undefined) {
            const dp = opt(value.dp, opt(column["x-decimalPlaces"], 0))
            const extUnits = column.ExtUnits
            const unit = extUnits ? opt(extUnits.unitUnicode, opt(extUnits.unitAscii, "")) : ""
            return (value.num / value.den).toFixed(dp) + (unit ? " " + unit : "")
        }
        return String(value)
    }

    // `bind` is the wire object morph::views::viewSchemaJson<V>() emits for
    // v-rowAction/v-actions: {actionField: rowField, ...} (a plain JSON
    // object, matching ActionDescriptor::bind's std::span<const BindEntry>
    // serialised by buildActionNode() -- NOT an array of {actionField,
    // rowField} entries).
    function bindBodyJson(bind, row) {
        const parts = []
        for (const actionField in (bind || {}))
            parts.push(JSON.stringify(actionField) + ":" + JSON.stringify(row[bind[actionField]]))
        return "{" + parts.join(",") + "}"
    }

    function openEditor(row) {
        root.editorRow = row
    }

    function closeEditor() {
        root.editorRow = null
    }

    // bind is the only prefill mechanic (docs/spec/forms/views.md,
    // "Dispatch: the screen is still just action calls") — a form field not
    // named in v-rowAction's bind starts at its own default, unprefilled.
    function prefill(form) {
        if (!form)
            return
        // Clear first, always. modalForm/detailForm are single instances
        // created once inside their Dialog and reused for every row, and the
        // loop below only writes the fields v-rowAction names in `bind` --
        // so without this, anything else kept the value left there while
        // editing the *previous* row. Since DynamicForm.revalidate()
        // auto-submits the moment the form is `ready`, opening row 2 after
        // editing row 1 fired the row action with row 2's id and row 1's
        // leftover values: a silent write of data the user neither entered nor
        // saw. Done unconditionally (before the early return below) so closing
        // the editor also leaves a clean form behind.
        form.resetFields()

        const rowAction = root.view["v-rowAction"]
        if (!rowAction || !root.editorRow)
            return
        const bind = rowAction.bind || {}
        for (const actionField in bind) {
            // Setting `text` (not calling form.setFieldValue directly) is
            // deliberate: it drives the *same* TextField.onTextChanged path
            // a user's own typing does, so both the visible control and
            // form.fieldValues end up in sync from this one assignment. The
            // raw (unquoted) text is what fieldValues holds -- fieldJsonLiteral
            // applies JSON.stringify itself when it later reads this field.
            const control = root.findControlByObjectName(form, "field_" + actionField)
            if (control)
                control.text = String(root.editorRow[bind[actionField]])
        }
    }

    function fireRowAction(descriptor, row) {
        if (!root.controller)
            return
        if (descriptor.confirm) {
            confirmDialog.pendingAction = descriptor
            confirmDialog.pendingRow = row
            confirmDialog.open()
            return
        }
        root.controller.submitIfValid(descriptor.action, root.bindBodyJson(descriptor.bind || {}, row))
    }

    function fireCollectionAction(descriptor) {
        if (root.controller)
            root.controller.submitIfValid(descriptor.action, "{}")
    }

    onEditorRowChanged: {
        root.prefill(modalForm)
        root.prefill(detailForm)
    }

    Connections {
        target: root.controller
        function onReplyReceived(actionType, ok, payload) {
            if (actionType === root.view["v-query"]) {
                if (!ok)
                    return
                let parsed
                try { parsed = JSON.parse(payload) } catch (ignored) { return }
                root.rows = root.extractRows(parsed)
                return
            }
            const rowAction = root.view["v-rowAction"]
            const isRowAction = rowAction !== undefined && rowAction.action === actionType
            const isListedAction = (root.view["v-actions"] || []).some(a => a.action === actionType)
            if (ok && (isRowAction || isListedAction)) {
                root.closeEditor()
                root.populate()   // re-run the query to refresh (no push channel)
            }
        }
    }

    Dialog {
        id: confirmDialog
        property var pendingAction: null
        property var pendingRow: null
        objectName: "confirmDialog"
        title: "Confirm"
        modal: true
        standardButtons: Dialog.Yes | Dialog.No
        Label { text: "Are you sure?" }
        onAccepted: {
            if (confirmDialog.pendingAction && root.controller) {
                root.controller.submitIfValid(confirmDialog.pendingAction.action,
                    root.bindBodyJson(confirmDialog.pendingAction.bind || {}, confirmDialog.pendingRow))
            }
            confirmDialog.pendingAction = null
            confirmDialog.pendingRow = null
        }
    }

    // Collection kind: the row editor is a modal (list-plus-modal fallback of
    // the master-detail split — docs/spec/forms/views.md, "Design
    // decisions"). Master-detail vs. collection is a rendering choice, not a
    // schema difference.
    Dialog {
        id: editorDialog
        objectName: "editorDialog"
        visible: !root.isMasterDetail && root.editorRow !== null
        modal: true
        title: root.view["v-rowAction"] ? String(root.view["v-rowAction"].action) : ""
        onClosed: root.closeEditor()

        DynamicForm {
            id: modalForm
            actionType: root.view["v-rowAction"] ? root.view["v-rowAction"].action : ""
            schema: root.schemas[modalForm.actionType] || ({})
            controller: root.controller
        }
    }

    RowLayout {
        anchors.left: parent.left
        anchors.right: parent.right
        spacing: 8

        ColumnLayout {
            Layout.fillWidth: true
            spacing: 4

            Label {
                text: root.opt(root.view["v-title"], root.viewId)
                font.bold: true
                font.pixelSize: 16
            }

            RowLayout {
                spacing: 8

                Repeater {
                    model: root.visibleColumns
                    Label {
                        required property var modelData
                        text: modelData.label
                        font.bold: true
                        Layout.preferredWidth: 120
                    }
                }
                Item { Layout.fillWidth: true }
                Repeater {
                    model: root.collectionScopeActions
                    Button {
                        required property var modelData
                        objectName: "collectionAction_" + modelData.action
                        text: modelData.label
                        onClicked: root.fireCollectionAction(modelData)
                    }
                }
            }

            Repeater {
                model: root.rows
                RowLayout {
                    id: rowDelegate
                    required property var modelData
                    Layout.fillWidth: true
                    spacing: 8

                    Repeater {
                        model: root.visibleColumns
                        Label {
                            required property var modelData
                            // Row key suffix keeps this objectName unique across
                            // rows (every row's Repeater otherwise reuses the
                            // same column field name) so a test can target one
                            // row's cell unambiguously.
                            objectName: "cell_" + modelData.field + "_"
                                        + JSON.stringify(rowDelegate.modelData[root.opt(root.view["v-rowKey"], "id")])
                            text: root.formatCell(rowDelegate.modelData, modelData)
                            Layout.preferredWidth: 120
                        }
                    }

                    Button {
                        visible: root.view["v-rowAction"] !== undefined
                        objectName: "rowOpen_" + JSON.stringify(rowDelegate.modelData[root.opt(root.view["v-rowKey"], "id")])
                        text: "Open"
                        onClicked: root.openEditor(rowDelegate.modelData)
                    }

                    Repeater {
                        model: root.rowScopeActions
                        Button {
                            required property var modelData
                            objectName: "rowAction_" + modelData.action + "_"
                                        + JSON.stringify(rowDelegate.modelData[root.opt(root.view["v-rowKey"], "id")])
                            text: modelData.label
                            onClicked: root.fireRowAction(modelData, rowDelegate.modelData)
                        }
                    }
                }
            }
        }

        // Master-detail kind: the same rowAction editor, live-bound to the
        // selection, rendered as a split pane instead of a modal.
        DynamicForm {
            id: detailForm
            visible: root.isMasterDetail && root.editorRow !== null
            Layout.preferredWidth: 260
            actionType: root.view["v-rowAction"] ? root.view["v-rowAction"].action : ""
            schema: root.schemas[detailForm.actionType] || ({})
            controller: root.controller
        }
    }

    Component.onCompleted: root.populate()
}
