// SPDX-License-Identifier: Apache-2.0
//
// Entry point of the QML forms demo: parses the schema set exposed by the
// controller and instantiates one DynamicForm per action. Nothing in this
// file (or DynamicForm.qml) knows the actions' fields — the schema is the
// only contract.

pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import MorphForms

ApplicationWindow {
    id: root
    width: 560
    height: 760
    visible: true
    title: "morph forms — QML renderer"

    property var schemas: JSON.parse(controller.schemasJson)

    FormsController {
        id: controller
    }

    ScrollView {
        anchors.fill: parent
        contentWidth: availableWidth

        ColumnLayout {
            width: parent.width
            spacing: 8

            Label {
                Layout.fillWidth: true
                Layout.margins: 12
                wrapMode: Text.Wrap
                opacity: 0.7
                text: "Each form below is rendered at runtime from a JSON Schema generated by "
                      + "morph::forms::schemaJson<A>() — order, units, decimal steps, bounds and "
                      + "required fields all come from the schema. Submits travel as wire envelopes "
                      + "through an in-process RemoteServer."
            }

            Repeater {
                model: Object.keys(root.schemas)

                DynamicForm {
                    required property string modelData
                    Layout.fillWidth: true
                    Layout.leftMargin: 12
                    Layout.rightMargin: 12
                    actionType: modelData
                    schema: root.schemas[modelData]
                    controller: controller
                }
            }

            Item { Layout.preferredHeight: 12 }
        }
    }
}
