// SPDX-License-Identifier: Apache-2.0

/// @file
/// morph forms demo — see how JSON-Forms-style schemas drive a GUI.
///
/// Modes:
///   morph_forms_demo --schemas            print the generated action schemas
///   morph_forms_demo --emit-html [path]   write a self-contained demo page
///                                         (default: forms_demo.html)
///   morph_forms_demo                      REPL: execute pasted action lines
///
/// The intended loop: `--emit-html`, open the page in a browser, fill a form
/// (rendered purely from the schema), copy the produced line, paste it into
/// the REPL — which dispatches it through the same type-erased
/// `ActionDispatcher` seam `RemoteServer` uses — and read the model's reply.

#include <morph/core/bridge.hpp>

#include <exception>
#include <fstream>
#include <iostream>
#include <print>
#include <string>
#include <string_view>
#include <vector>

#include "lab_model.hpp"
#include "lab_schemas.hpp"

namespace {

using lab::schemasJson;

/// @brief Escapes `<` as `<` so schema text (descriptions, unit labels)
///        can never terminate the surrounding `<script>` element. `<` only
///        occurs inside JSON strings, where the escape is valid.
[[nodiscard]] std::string escapeForScriptEmbed(const std::string& json) {
    std::string out;
    out.reserve(json.size());
    for (char ch : json) {
        if (ch == '<') {
            out += "\\u003C";
        } else {
            out += ch;
        }
    }
    return out;
}

// The demo page, split around the embedded schemas object. Everything is
// inline (no CDN, no framework): the point is that the schema alone carries
// enough to build the GUI.
constexpr std::string_view kHtmlHead = R"HTML(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>morph forms demo</title>
<style>
:root { color-scheme: light dark; --card:#ffffff; --line:#d0d4da; --muted:#647084; --accent:#2563eb; --bg:#f3f5f8; --err:#b91c1c; }
@media (prefers-color-scheme: dark) { :root { --card:#1b1e24; --line:#3a3f47; --muted:#9aa4b2; --accent:#60a5fa; --bg:#101216; --err:#f87171; } }
body { font:15px/1.45 system-ui,sans-serif; background:var(--bg); color:inherit; margin:0; padding:2rem 1rem; }
main { max-width:640px; margin:auto; }
h1 { font-size:1.4rem; margin:0 0 .3rem; }
p.hint { color:var(--muted); margin:.2rem 0 1rem; }
form { background:var(--card); border:1px solid var(--line); border-radius:10px; padding:1rem 1.25rem 1.25rem; margin:1.25rem 0; }
h2 { font-size:1.05rem; margin:.1rem 0 .6rem; }
label { display:block; margin:.7rem 0 .15rem; font-weight:600; }
label .req { color:var(--err); }
.desc { color:var(--muted); font-size:.85rem; margin:0 0 .25rem; }
.row { display:flex; align-items:center; gap:.5rem; }
input, select { flex:1; font:inherit; padding:.45rem .6rem; border:1px solid var(--line); border-radius:6px; background:transparent; color:inherit; }
.unit { min-width:3.2rem; color:var(--muted); }
select.unit { min-width:4.5rem; padding:.35rem .4rem; }
button { margin-top:1rem; font:inherit; padding:.5rem 1rem; border-radius:6px; border:0; background:var(--accent); color:#fff; cursor:pointer; }
button:disabled { opacity:.45; cursor:not-allowed; }
button.mini { margin-top:0; padding:.35rem .6rem; background:transparent; border:1px solid var(--line); color:var(--muted); }
pre { background:rgba(127,127,127,.12); padding:.6rem .8rem; border-radius:6px; overflow-x:auto; font-size:.8rem; white-space:pre-wrap; }
</style>
</head>
<body>
<main>
<h1>morph forms demo</h1>
<p class="hint">Each form below is rendered at runtime from a JSON Schema generated by
<code>morph::forms::schemaJson&lt;A&gt;()</code> out of the C++ action structs &mdash; field order
(<code>x-order</code>), units (<code>ExtUnits</code>), decimal steps (<code>x-decimalPlaces</code>),
bounds, required-ness (<code>required</code>), date-time inputs (<code>format</code>) and combo boxes
whose options were served by the action named in <code>x-optionsAction</code> all come from the schema,
nothing is hardcoded here.
Fill a form and copy the produced line into the <code>morph_forms_demo</code> REPL to execute it
against the real model.</p>
<div id="forms"></div>
<h2>last built line</h2>
<pre id="log">fill a form and press its button&hellip;</pre>
</main>
<script>
const SCHEMAS = )HTML";

constexpr std::string_view kHtmlTail = R"HTML(;

// __MORPH_MATH_BEGIN__ (pure helpers; extracted verbatim by test_html_math.mjs)
// Follow a $ref into $defs; attributes declared on the field win.
function resolve(schema, prop) {
  if (prop && prop.$ref) {
    const def = (schema.$defs || {})[prop.$ref.split('/').pop()] || {};
    return Object.assign({}, def, prop);
  }
  return prop || {};
}
function typeSet(p) { const t = p.type; return new Set(Array.isArray(t) ? t : (t ? [t] : [])); }

// Digits of a decimal string as an exact scaled BigInt (value * 10^dp).
function scaledBig(text, dp) {
  const neg = text.startsWith('-');
  const [intPart, fracPart = ''] = (neg ? text.slice(1) : text).split('.');
  const frac = (fracPart + '0'.repeat(dp)).slice(0, dp);
  const scaled = BigInt(intPart || '0') * 10n ** BigInt(dp) + BigInt(frac || '0');
  return neg ? -scaled : scaled;
}

// Exact rational JSON for a value typed in `unit` ({decimals,num,den}: the
// exact unit-to-canonical ratio). The payload always carries the canonical
// unit: value_canonical = digits/10^decimals * num/den.
function rationalJson(text, unit, canonDp) {
  const num = scaledBig(text, unit.decimals) * BigInt(unit.num);
  const den = 10n ** BigInt(unit.decimals) * BigInt(unit.den);
  return '{"num":' + num.toString() + ',"den":' + den.toString() + ',"dp":' + canonDp + '}';
}

function divRoundBig(a, b) {  // round half away from zero; b > 0
  const neg = a < 0n;
  const abs = neg ? -a : a;
  const q = (abs * 2n + b) / (2n * b);
  return neg ? -q : q;
}

function formatScaled(value, dp) {  // BigInt value * 10^-dp -> decimal string
  const neg = value < 0n;
  let digits = (neg ? -value : value).toString();
  if (dp === 0) return (neg ? '-' : '') + digits;
  digits = digits.padStart(dp + 1, '0');
  return (neg ? '-' : '') + digits.slice(0, -dp) + '.' + digits.slice(-dp);
}

// Recalculate a decimal string from one unit into another, exactly, rounded
// to the target unit's decimals.
function convertText(text, from, to) {
  if (!/^-?\d+(\.\d+)?$/.test(text)) return '';
  const numer = scaledBig(text, from.decimals) * BigInt(from.num) * BigInt(to.den) * 10n ** BigInt(to.decimals);
  const denom = BigInt(from.den) * BigInt(to.num) * 10n ** BigInt(from.decimals);
  return formatScaled(divRoundBig(numer, denom), to.decimals);
}
// __MORPH_MATH_END__

function build() {
  const host = document.getElementById('forms');
  for (const [action, schema] of Object.entries(SCHEMAS)) {
    const required = new Set(schema.required || []);
    const names = Object.keys(schema.properties || {})
      .sort((a, b) => ((schema.properties[a]['x-order'] ?? 0) - (schema.properties[b]['x-order'] ?? 0)));

    const form = document.createElement('form');
    const title = document.createElement('h2');
    title.textContent = action;
    form.appendChild(title);

    const fields = [];
    for (const name of names) {
      const raw = schema.properties[name];
      const p = resolve(schema, raw);
      const types = typeSet(p);
      const isQuantity = ('x-decimalPlaces' in raw) || ('x-decimalPlaces' in p);
      const req = required.has(name);

      const label = document.createElement('label');
      label.append(name);
      if (req) { const s = document.createElement('span'); s.className = 'req'; s.textContent = ' *'; label.appendChild(s); }
      form.appendChild(label);
      if (p.description) { const d = document.createElement('p'); d.className = 'desc'; d.textContent = p.description; form.appendChild(d); }

      const row = document.createElement('div');
      row.className = 'row';
      const optionsAction = raw['x-optionsAction'] || p['x-optionsAction'];
      let control;
      let kind;
      if (optionsAction) {
        // Combo box: options were served by the declared action; each
        // <option>'s DOM value is the row value as a JSON literal.
        kind = 'choice';
        control = document.createElement('select');
        const blank = document.createElement('option');
        blank.value = '';
        blank.textContent = '— select —';
        control.appendChild(blank);
        for (const o of (OPTIONS[optionsAction] || [])) {
          const opt = document.createElement('option');
          opt.value = JSON.stringify(o.value);
          opt.textContent = o.label;
          control.appendChild(opt);
        }
      } else if (isQuantity) {
        kind = 'quantity';
        control = document.createElement('input');
        const dp = raw['x-decimalPlaces'] ?? p['x-decimalPlaces'] ?? 3;
        control.type = 'number';
        control.step = (10 ** -dp).toFixed(dp);
        control.dataset.dp = dp;
      } else if (p.format === 'date-time') {
        // The demo treats the entered time as UTC (appends 'Z'). The native
        // datetime-local control is the picker; "now" fills the current UTC time.
        kind = 'datetime';
        control = document.createElement('input');
        control.type = 'datetime-local';
        control.step = '1';
        const nowBtn = document.createElement('button');
        nowBtn.type = 'button';
        nowBtn.className = 'mini';
        nowBtn.textContent = 'now';
        nowBtn.addEventListener('click', () => {
          control.value = new Date().toISOString().slice(0, 19);
          control.dispatchEvent(new Event('input', { bubbles: true }));
        });
        row.appendChild(nowBtn);
      } else if (types.has('integer')) {
        kind = 'integer';
        control = document.createElement('input');
        control.type = 'number';
        control.step = '1';
      } else {
        kind = 'string';
        control = document.createElement('input');
        control.type = 'text';
      }
      if (p.minimum !== undefined) control.min = p.minimum;
      if (p.maximum !== undefined) control.max = p.maximum;
      row.appendChild(control);

      // Unit display: a plain suffix, or a selector when the unit system
      // declares convertible alternatives (x-unitAlternatives) — switching
      // recalculates the entered value exactly.
      const unitText = (p.ExtUnits && (p.ExtUnits.unitUnicode || p.ExtUnits.unitAscii)) || '';
      const field = { name: name, input: control, kind: kind, req: req };
      if (kind === 'quantity') {
        const canonDp = +control.dataset.dp;
        field.canonDp = canonDp;
        field.units = [{ display: unitText || '(1)', decimals: canonDp, num: 1, den: 1 }];
        for (const alt of (raw['x-unitAlternatives'] || p['x-unitAlternatives'] || [])) {
          field.units.push({ display: alt.display || alt.id, decimals: alt.decimals, num: alt.num, den: alt.den });
        }
        field.unitIndex = 0;
      }
      if (field.units && field.units.length > 1) {
        const unitSelect = document.createElement('select');
        unitSelect.className = 'unit';
        unitSelect.style.flex = '0 0 auto';
        field.units.forEach((u, index) => {
          const opt = document.createElement('option');
          opt.value = index;
          opt.textContent = u.display;
          unitSelect.appendChild(opt);
        });
        unitSelect.addEventListener('change', () => {
          const fromUnit = field.units[field.unitIndex];
          field.unitIndex = +unitSelect.value;
          const toUnit = field.units[field.unitIndex];
          if (control.value.trim() !== '') control.value = convertText(control.value.trim(), fromUnit, toUnit);
          control.step = (10 ** -toUnit.decimals).toFixed(toUnit.decimals);
        });
        row.appendChild(unitSelect);
      } else if (unitText) {
        const u = document.createElement('span');
        u.className = 'unit';
        u.textContent = unitText;
        row.appendChild(u);
      }
      form.appendChild(row);
      fields.push(field);
    }

    const btn = document.createElement('button');
    btn.type = 'submit';
    btn.textContent = 'build & copy REPL line';
    form.appendChild(btn);
    const out = document.createElement('pre');
    form.appendChild(out);

    const compose = () => {
      // The body is assembled as JSON text (not via JSON.stringify) so BigInt
      // rational digits and int64-sized integers stay exact.
      const parts = [];
      let ok = true;
      for (const f of fields) {
        const t = f.input.value.trim();
        if (t === '') { if (f.req) ok = false; continue; }
        if (f.kind === 'choice') {
          parts.push(JSON.stringify(f.name) + ':' + t);  // already a JSON literal
        } else if (f.kind === 'datetime') {
          if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?$/.test(t)) { ok = false; continue; }
          parts.push(JSON.stringify(f.name) + ':' + JSON.stringify((t.length === 16 ? t + ':00' : t) + 'Z'));
        } else if (f.kind === 'quantity') {
          if (!/^-?\d+(\.\d+)?$/.test(t) || !f.input.checkValidity()) { ok = false; continue; }
          parts.push(JSON.stringify(f.name) + ':' + rationalJson(t, f.units[f.unitIndex], f.canonDp));
        } else if (f.kind === 'integer') {
          if (!/^-?\d+$/.test(t) || !f.input.checkValidity()) { ok = false; continue; }
          // Normalise "007" -> "7": JSON forbids leading zeros in numbers.
          parts.push(JSON.stringify(f.name) + ':' + t.replace(/^(-?)0+(?=\d)/, '$1'));
        } else {
          parts.push(JSON.stringify(f.name) + ':' + JSON.stringify(t));
        }
      }
      btn.disabled = !ok;
      out.textContent = ok ? (action + ' {' + parts.join(',') + '}') : '… fill the required (*) fields';
      return ok ? out.textContent : null;
    };
    form.addEventListener('input', compose);
    form.addEventListener('change', compose);
    form.addEventListener('submit', (ev) => {
      ev.preventDefault();
      const line = compose();
      if (!line) return;
      const log = document.getElementById('log');
      if (navigator.clipboard) {
        navigator.clipboard.writeText(line).then(
          () => { log.textContent = line + '\n\n(copied — paste into the morph_forms_demo REPL)'; },
          () => { log.textContent = line + '\n\n(clipboard blocked — copy the line above manually)'; });
      } else {
        log.textContent = line + '\n\n(clipboard unavailable here — copy the line above manually)';
      }
    });
    compose();
    host.appendChild(form);
  }
}
build();
</script>
</body>
</html>
)HTML";

/// @brief Resolves every `x-optionsAction` declared in the schemas by
///        executing that action and mapping its result rows to
///        `{value,label}` pairs — the static page cannot fetch live, so the
///        options are resolved at emit time (a live client fetches instead).
[[nodiscard]] std::string optionsJson() {
    glz::generic_u64 schemas{};
    if (glz::read_json(schemas, schemasJson())) {
        return "{}";
    }

    auto holder = morph::model::detail::ModelRegistryFactory::instance().create("LabModel");
    std::string out = "{";
    bool firstAction = true;
    for (auto& [actionName, schema] : schemas.get_object()) {
        static_cast<void>(actionName);
        if (!schema.contains("properties")) {
            continue;
        }
        for (auto& [fieldName, property] : schema["properties"].get_object()) {
            static_cast<void>(fieldName);
            if (!property.contains("x-optionsAction")) {
                continue;
            }
            auto const optionsAction = property["x-optionsAction"].get_string();
            auto const valueField = property["x-optionValue"].get_string();
            auto const labelField = property["x-optionLabel"].get_string();
            if (out.contains("\"" + optionsAction + "\"")) {
                continue;  // already resolved for another field
            }

            std::string rowsJson;
            try {
                rowsJson = morph::model::detail::ActionDispatcher::instance().dispatch("LabModel", optionsAction,
                                                                                       *holder, "{}");
            } catch (const std::exception&) {
                continue;  // options provider failed; render as free input
            }
            glz::generic_u64 result{};
            if (glz::read_json(result, rowsJson)) {
                continue;
            }
            // Rows are the result itself when it is an array, otherwise the
            // first array-valued member of the result object.
            glz::generic_u64* rows = result.is_array() ? &result : nullptr;
            if (rows == nullptr && result.is_object()) {
                for (auto& [memberName, member] : result.get_object()) {
                    static_cast<void>(memberName);
                    if (member.is_array()) {
                        rows = &member;
                        break;
                    }
                }
            }
            if (rows == nullptr) {
                continue;
            }

            if (!firstAction) {
                out += ',';
            }
            firstAction = false;
            out += '"';
            out += optionsAction;
            out += "\":[";
            bool firstRow = true;
            for (auto& row : rows->get_array()) {
                if (!row.contains(valueField) || !row.contains(labelField)) {
                    continue;
                }
                if (!firstRow) {
                    out += ',';
                }
                firstRow = false;
                out += "{\"value\":";
                out += glz::write_json(row[valueField]).value_or("null");
                out += ",\"label\":";
                out += glz::write_json(row[labelField]).value_or("\"?\"");
                out += '}';
            }
            out += ']';
        }
    }
    out += '}';
    return out;
}

void runRepl() {
    std::println("morph forms demo — REPL (model: LabModel)");
    std::println("paste a line from the HTML page, or try:");
    std::cout << R"(  ComputeDryDensity {"massDry":{"num":26505,"den":10,"dp":1},"volume":{"num":1,"den":1,"dp":3}})"
              << '\n'
              << R"(  RecordMeasurement {"sampleId":7,"measuredAt":"2026-07-05T14:30:00Z","density":{"num":5301,"den":2,"dp":1},"note":"demo"})"
              << '\n'
              << R"(  ListSamples {})" << '\n';
    std::println("(quit with 'exit' or Ctrl-D; schemas via --schemas)");

    // The same type-erased seam RemoteServer dispatches through: string ids
    // in, JSON payload in, JSON result out.
    auto holder = morph::model::detail::ModelRegistryFactory::instance().create("LabModel");
    std::string line;
    while (std::getline(std::cin, line)) {
        // Trim both ends (including the \r of CRLF-pasted lines).
        auto const begin = line.find_first_not_of(" \t\r");
        if (begin == std::string::npos) {
            continue;
        }
        line = line.substr(begin, line.find_last_not_of(" \t\r") - begin + 1);
        if (line == "exit" || line == "quit") {
            break;
        }
        auto const separator = line.find_first_of(" \t");
        auto const action = line.substr(0, separator);
        auto payload = std::string{"{}"};
        if (separator != std::string::npos) {
            auto const payloadBegin = line.find_first_not_of(" \t", separator);
            if (payloadBegin != std::string::npos) {
                payload = line.substr(payloadBegin);
            }
        }
        try {
            auto const result =
                morph::model::detail::ActionDispatcher::instance().dispatch("LabModel", action, *holder, payload);
            std::println("ok:  {}", result);
        } catch (const std::exception& error) {
            std::println("err: {}", error.what());
        }
    }
}

}  // namespace

int main(int argc, char** argv) {
    std::vector<std::string_view> args(argv + 1, argv + argc);

    if (!args.empty() && args[0] == "--schemas") {
        std::println("{}", glz::prettify_json(schemasJson()));
        return 0;
    }

    if (!args.empty() && args[0] == "--emit-html") {
        auto const path = std::string{args.size() > 1 ? args[1] : std::string_view{"forms_demo.html"}};
        std::ofstream file{path, std::ios::binary};
        if (!file) {
            std::println(stderr, "error: cannot write {}", path);
            return 1;
        }
        file << kHtmlHead << escapeForScriptEmbed(schemasJson()) << ";\nconst OPTIONS = "
             << escapeForScriptEmbed(optionsJson()) << kHtmlTail;
        std::println("wrote {} — open it in a browser, then run ./morph_forms_demo for the REPL", path);
        return 0;
    }

    runRepl();
    return 0;
}
