// SPDX-License-Identifier: Apache-2.0

/// @file
/// morph forms demo — see how JSON-Forms-style schemas drive a GUI.
///
/// Modes:
///   morph_forms_demo --schemas            print the generated action schemas
///   morph_forms_demo --emit-html [path]   write a self-contained demo page
///                                         (default: forms_demo.html)
///   morph_forms_demo                      REPL: execute pasted action lines
///
/// The intended loop: `--emit-html`, open the page in a browser, fill a form
/// (rendered purely from the schema), copy the produced line, paste it into
/// the REPL — which dispatches it through the same type-erased
/// `ActionDispatcher` seam `RemoteServer` uses — and read the model's reply.

#include <exception>
#include <fstream>
#include <iostream>
#include <print>
#include <string>
#include <string_view>
#include <vector>

#include "lab_model.hpp"
#include "lab_schemas.hpp"

namespace {

using lab::schemasJson;

// The demo page, split around the embedded schemas object. Everything is
// inline (no CDN, no framework): the point is that the schema alone carries
// enough to build the GUI.
constexpr std::string_view kHtmlHead = R"HTML(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>morph forms demo</title>
<style>
:root { color-scheme: light dark; --card:#ffffff; --line:#d0d4da; --muted:#647084; --accent:#2563eb; --bg:#f3f5f8; --err:#b91c1c; }
@media (prefers-color-scheme: dark) { :root { --card:#1b1e24; --line:#3a3f47; --muted:#9aa4b2; --accent:#60a5fa; --bg:#101216; --err:#f87171; } }
body { font:15px/1.45 system-ui,sans-serif; background:var(--bg); color:inherit; margin:0; padding:2rem 1rem; }
main { max-width:640px; margin:auto; }
h1 { font-size:1.4rem; margin:0 0 .3rem; }
p.hint { color:var(--muted); margin:.2rem 0 1rem; }
form { background:var(--card); border:1px solid var(--line); border-radius:10px; padding:1rem 1.25rem 1.25rem; margin:1.25rem 0; }
h2 { font-size:1.05rem; margin:.1rem 0 .6rem; }
label { display:block; margin:.7rem 0 .15rem; font-weight:600; }
label .req { color:var(--err); }
.desc { color:var(--muted); font-size:.85rem; margin:0 0 .25rem; }
.row { display:flex; align-items:center; gap:.5rem; }
input { flex:1; font:inherit; padding:.45rem .6rem; border:1px solid var(--line); border-radius:6px; background:transparent; color:inherit; }
.unit { min-width:3.2rem; color:var(--muted); }
button { margin-top:1rem; font:inherit; padding:.5rem 1rem; border-radius:6px; border:0; background:var(--accent); color:#fff; cursor:pointer; }
button:disabled { opacity:.45; cursor:not-allowed; }
pre { background:rgba(127,127,127,.12); padding:.6rem .8rem; border-radius:6px; overflow-x:auto; font-size:.8rem; white-space:pre-wrap; }
</style>
</head>
<body>
<main>
<h1>morph forms demo</h1>
<p class="hint">Each form below is rendered at runtime from a JSON Schema generated by
<code>morph::forms::schemaJson&lt;A&gt;()</code> out of the C++ action structs &mdash; field order
(<code>x-order</code>), units (<code>ExtUnits</code>), decimal steps (<code>x-decimalPlaces</code>),
bounds and required-ness (<code>required</code>) all come from the schema, nothing is hardcoded here.
Fill a form and copy the produced line into the <code>morph_forms_demo</code> REPL to execute it
against the real model.</p>
<div id="forms"></div>
<h2>last built line</h2>
<pre id="log">fill a form and press its button&hellip;</pre>
</main>
<script>
const SCHEMAS = )HTML";

constexpr std::string_view kHtmlTail = R"HTML(;

// Follow a $ref into $defs; attributes declared on the field win.
function resolve(schema, prop) {
  if (prop && prop.$ref) {
    const def = (schema.$defs || {})[prop.$ref.split('/').pop()] || {};
    return Object.assign({}, def, prop);
  }
  return prop || {};
}
function typeSet(p) { const t = p.type; return new Set(Array.isArray(t) ? t : (t ? [t] : [])); }

// "2650.5" + dp -> exact {num, den, dp} (the Rational wire object).
function toRational(text, dp) {
  const neg = text.startsWith('-');
  const [intPart, fracPart = ''] = (neg ? text.slice(1) : text).split('.');
  const frac = (fracPart + '0'.repeat(dp)).slice(0, dp);
  let num = BigInt(intPart || '0') * 10n ** BigInt(dp) + BigInt(frac || '0');
  if (neg) num = -num;
  return { num: Number(num), den: Number(10n ** BigInt(dp)), dp: dp };
}

function build() {
  const host = document.getElementById('forms');
  for (const [action, schema] of Object.entries(SCHEMAS)) {
    const required = new Set(schema.required || []);
    const names = Object.keys(schema.properties || {})
      .sort((a, b) => ((schema.properties[a]['x-order'] ?? 0) - (schema.properties[b]['x-order'] ?? 0)));

    const form = document.createElement('form');
    const title = document.createElement('h2');
    title.textContent = action;
    form.appendChild(title);

    const fields = [];
    for (const name of names) {
      const raw = schema.properties[name];
      const p = resolve(schema, raw);
      const types = typeSet(p);
      const isQuantity = ('x-decimalPlaces' in raw) || ('x-decimalPlaces' in p);
      const req = required.has(name);

      const label = document.createElement('label');
      label.append(name);
      if (req) { const s = document.createElement('span'); s.className = 'req'; s.textContent = ' *'; label.appendChild(s); }
      form.appendChild(label);
      if (p.description) { const d = document.createElement('p'); d.className = 'desc'; d.textContent = p.description; form.appendChild(d); }

      const row = document.createElement('div');
      row.className = 'row';
      const input = document.createElement('input');
      let kind;
      if (isQuantity) {
        kind = 'quantity';
        const dp = raw['x-decimalPlaces'] ?? p['x-decimalPlaces'] ?? 3;
        input.type = 'number';
        input.step = (10 ** -dp).toFixed(dp);
        input.dataset.dp = dp;
      } else if (types.has('integer')) {
        kind = 'integer';
        input.type = 'number';
        input.step = '1';
      } else {
        kind = 'string';
        input.type = 'text';
      }
      if (p.minimum !== undefined) input.min = p.minimum;
      if (p.maximum !== undefined) input.max = p.maximum;
      row.appendChild(input);
      const unit = (p.ExtUnits && (p.ExtUnits.unitUnicode || p.ExtUnits.unitAscii)) || '';
      if (unit) { const u = document.createElement('span'); u.className = 'unit'; u.textContent = unit; row.appendChild(u); }
      form.appendChild(row);
      fields.push({ name: name, input: input, kind: kind, req: req });
    }

    const btn = document.createElement('button');
    btn.type = 'submit';
    btn.textContent = 'build & copy REPL line';
    form.appendChild(btn);
    const out = document.createElement('pre');
    form.appendChild(out);

    const compose = () => {
      const body = {};
      let ok = true;
      for (const f of fields) {
        const t = f.input.value.trim();
        if (t === '') { if (f.req) ok = false; continue; }
        if (f.kind === 'quantity') {
          if (!/^-?\d+(\.\d+)?$/.test(t) || !f.input.checkValidity()) { ok = false; continue; }
          body[f.name] = toRational(t, +f.input.dataset.dp);
        } else if (f.kind === 'integer') {
          if (!/^-?\d+$/.test(t) || !f.input.checkValidity()) { ok = false; continue; }
          body[f.name] = Number(t);
        } else {
          body[f.name] = t;
        }
      }
      btn.disabled = !ok;
      out.textContent = ok ? (action + ' ' + JSON.stringify(body)) : '… fill the required (*) fields';
      return ok ? out.textContent : null;
    };
    form.addEventListener('input', compose);
    form.addEventListener('submit', (ev) => {
      ev.preventDefault();
      const line = compose();
      if (!line) return;
      if (navigator.clipboard) navigator.clipboard.writeText(line);
      document.getElementById('log').textContent = line + '\n\n(copied — paste into the morph_forms_demo REPL)';
    });
    compose();
    host.appendChild(form);
  }
}
build();
</script>
</body>
</html>
)HTML";

void runRepl() {
    std::println("morph forms demo — REPL (model: LabModel)");
    std::println("paste a line from the HTML page, or try:");
    std::cout << R"(  ComputeDryDensity {"massDry":{"num":26505,"den":10,"dp":1},"volume":{"num":1,"den":1,"dp":3}})"
              << '\n'
              << R"(  RecordMeasurement {"sampleId":7,"density":{"num":5301,"den":2,"dp":1},"note":"demo"})" << '\n';
    std::println("(quit with 'exit' or Ctrl-D; schemas via --schemas)");

    // The same type-erased seam RemoteServer dispatches through: string ids
    // in, JSON payload in, JSON result out.
    auto holder = morph::model::detail::ModelRegistryFactory::instance().create("LabModel");
    std::string line;
    while (std::getline(std::cin, line)) {
        auto const begin = line.find_first_not_of(" \t");
        if (begin == std::string::npos) {
            continue;
        }
        line = line.substr(begin);
        if (line == "exit" || line == "quit") {
            break;
        }
        auto const separator = line.find(' ');
        auto const action = line.substr(0, separator);
        auto const payload = separator == std::string::npos ? std::string{"{}"} : line.substr(separator + 1);
        try {
            auto const result =
                morph::model::detail::ActionDispatcher::instance().dispatch("LabModel", action, *holder, payload);
            std::println("ok:  {}", result);
        } catch (const std::exception& error) {
            std::println("err: {}", error.what());
        }
    }
}

}  // namespace

int main(int argc, char** argv) {
    std::vector<std::string_view> args(argv + 1, argv + argc);

    if (!args.empty() && args[0] == "--schemas") {
        std::println("{}", glz::prettify_json(schemasJson()));
        return 0;
    }

    if (!args.empty() && args[0] == "--emit-html") {
        auto const path = std::string{args.size() > 1 ? args[1] : std::string_view{"forms_demo.html"}};
        std::ofstream file{path, std::ios::binary};
        if (!file) {
            std::println(stderr, "error: cannot write {}", path);
            return 1;
        }
        file << kHtmlHead << schemasJson() << kHtmlTail;
        std::println("wrote {} — open it in a browser, then run ./morph_forms_demo for the REPL", path);
        return 0;
    }

    runRepl();
    return 0;
}
